# This file defines the menus on the website. See the documentation for
# details: https://docs.bolt.cm/configuration/menus

main:
    - label: Servers
      title: This is the first menu item.
      path: "#page2"
      class: first
      ic: server
    - label: News
      path: entry/1
      ic: newspaper-o
    - label: Community
      path: pages/
      ic: users
    - label: Donate
      path: pages/
      ic: gift
    - label: Sign In
      path: pages/
      ic: sign-in
      class: login-button

